services:
  db:
    image: postgres:15-alpine
    container_name: shorts_factory_db
    restart: always
    environment:
      POSTGRES_USER: user_shorts
      POSTGRES_PASSWORD: password_shorts
      POSTGRES_DB: shorts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: shorts_factory_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shorts.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: